name: Build Project
on: [push]

jobs:
  # Build process
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring

      - name: Validate composer.json and composer.lock  
        run: composer validate

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv

